#!/bin/bash

TESTCASES=(1 2 3 4 5 6 7 8 9 10 11 12 13)
TESTDIR="examples"
WRONG="$(tput setaf 1)✗$(tput sgr0)"
CORRECT="$(tput setaf 2)✓$(tput sgr0)"
WARNING="$(tput setaf 3)⚠$(tput sgr0)"


function result {
    if [ "Same" = "$1"  ]
    then
        echo "${CORRECT}"
    else
        echo "${WRONG}"
    fi
}

echo '# Compiling...'
if ! make
then
    echo ''
    echo 'Compile fail.'
    exit 1
fi
echo ''

echo '# Testing Lambda evaluator'

for TC in "${TESTCASES[@]}"
do
    TFILE="${TESTDIR}/test${TC}"
    printf "Test %s..." "${TC}"
    COMM="./run ${TFILE}.l > ${TFILE}.out"

    eval "${COMMK}"

    if eval "${COMM}"
    then
        result $(eval "./comparer ${TFILE}.ans ${TFILE}.out")
    else
        echo "${WRONG}"
    fi
done
